// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:35beab6e-d9b8-4323-8595-6c0ca3bfd99d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_97FoL4nwU",
    "aws_user_pools_web_client_id": "8kl0d77jf1hm6f3a5mtflkn9v",
    "oauth": {}
};


export default awsmobile;
