// export { useSide } from "../redux/ducks/Side"
export { useTakerInfo } from "../redux/ducks/CareTaker"
export { useUserThoughts } from "../redux/ducks/thoughts"
export { useEstate } from "../redux/ducks/estate"
export { useExecutor } from "../redux/ducks/executor"
export { useBasicInfo } from "../redux/ducks/basicInfo"
